// <auto-generated />
using ConsoleAppSample2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleAppSample2.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20241219061448_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ConsoleAppSample2.DBModels.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("ConsoleAppSample2.DBModels.AccountView", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccountViews");
                });

            modelBuilder.Entity("ConsoleAppSample2.DBModels.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<long>("RefAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RefAccountId", "TransactionType");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ConsoleAppSample2.DBModels.AccountView", b =>
                {
                    b.HasOne("ConsoleAppSample2.DBModels.Account", "Account")
                        .WithOne("View")
                        .HasForeignKey("ConsoleAppSample2.DBModels.AccountView", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ConsoleAppSample2.DBModels.Transaction", b =>
                {
                    b.HasOne("ConsoleAppSample2.DBModels.Account", "Account")
                        .WithMany("ToTransactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConsoleAppSample2.DBModels.Account", "RefAccount")
                        .WithMany("FromTransactions")
                        .HasForeignKey("RefAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("RefAccount");
                });

            modelBuilder.Entity("ConsoleAppSample2.DBModels.Account", b =>
                {
                    b.Navigation("FromTransactions");

                    b.Navigation("ToTransactions");

                    b.Navigation("View")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
